---
- name: Install k3s on Amazon Linux 2
  hosts: all
  become: yes
  tasks:

    - name: Install dependencies
      yum:
        name:
          - curl
          - tar
          - wget
        state: present

    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s node to be ready
      shell: |
        sleep 10 && kubectl get node
      register: k3s_status
      retries: 5
      delay: 5
      until: k3s_status.rc == 0

    - name: Copy kubeconfig for ec2-user
      shell: |
        cp /etc/rancher/k3s/k3s.yaml /home/ec2-user/k3s.yaml
        chown ec2-user:ec2-user /home/ec2-user/k3s.yaml
